// apps/playground/src/DiagramRenderer.tsx
import { createEffect, on, onCleanup } from 'solid-js';
import type { OlliHandle } from 'olli';
import type { DiagramExample } from '../../docs/gallery/examples/types.js';

export function DiagramRenderer(props: { example: DiagramExample }) {
  let chartRef!: HTMLDivElement;
  let treeRef!: HTMLDivElement;

  createEffect(
    on(
      () => props.example.id,
      () => {
        let destroyMount: (() => void) | undefined;
        let handle: OlliHandle | undefined;
        let disposeBridge: (() => void) | undefined;
        let cancelled = false;

        onCleanup(() => {
          cancelled = true;
          disposeBridge?.();
          handle?.destroy();
          destroyMount?.();
          chartRef.innerHTML = '';
          treeRef.innerHTML = '';
        });

        (async () => {
          const [utils, olliJs] = await Promise.all([
            import('@umwelt-data/umwelt-utils'),
            import('olli'),
          ]);
          if (cancelled) return;

          const { svgElement, destroy } = await utils.mountBluefish(
            chartRef,
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            props.example.children as any,
          );
          destroyMount = destroy;
          if (cancelled) { destroy(); return; }

          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          handle = olliJs.olliDiagram(props.example.spec as any, treeRef);
          disposeBridge = utils.createBluefishBridge({ handle, svgElement }).destroy;
        })();
      },
    ),
  );

  return (
    <div class="renderer-grid">
      <div ref={chartRef} class="panel" role="img" aria-label={props.example.title} />
      <div ref={treeRef} class="panel" />
    </div>
  );
}

// packages/olli-solid/apps/docs/gallery/components/DiagramRenderer.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from 'vue';
import type { OlliHandle } from 'olli-js';
import type { DiagramExample } from '../examples/types.js';

const props = defineProps<{
  example: DiagramExample;
}>();

const chartContainer = ref<HTMLDivElement>();
const treeContainer = ref<HTMLDivElement>();

let destroyMount: (() => void) | undefined;
let handle: OlliHandle | undefined;
let disposeBridge: (() => void) | undefined;

async function mountDiagram() {
  if (!chartContainer.value || !treeContainer.value) return;

  const [utils, olliJs] = await Promise.all([
    import('@umwelt-data/umwelt-utils'),
    import('olli-js'),
  ]);

  const { svgElement, destroy } = await utils.mountBluefish(
    chartContainer.value,
    props.example.children,
  );
  destroyMount = destroy;

  handle = olliJs.olliDiagram(
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    props.example.spec as any,
    treeContainer.value,
  );

  const bridge = utils.createBluefishBridge({ handle, svgElement });
  disposeBridge = bridge.destroy;

  if (import.meta.env.DEV) {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (window as any).__olliGallery = { handle, svgElement, spec: props.example.spec };
  }
}

function teardown() {
  disposeBridge?.();
  disposeBridge = undefined;
  handle?.destroy();
  handle = undefined;
  destroyMount?.();
  destroyMount = undefined;
  if (chartContainer.value) chartContainer.value.innerHTML = '';
  if (treeContainer.value) treeContainer.value.innerHTML = '';
}

onMounted(() => void mountDiagram());
onBeforeUnmount(teardown);

watch(
  () => props.example.id,
  () => {
    teardown();
    void mountDiagram();
  },
);
</script>

<template>
  <div class="diagram-renderer">
    <div ref="chartContainer" class="diagram-chart" role="img" :aria-label="props.example.title" />
    <div ref="treeContainer" class="diagram-tree" />
  </div>
</template>

<style scoped>
.diagram-renderer {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 1.5rem;
  align-items: start;
}
.diagram-chart,
.diagram-tree {
  min-height: 12rem;
  border: 1px solid var(--vp-c-divider);
  border-radius: 6px;
  padding: 0.75rem;
  overflow: auto;
}
@media (max-width: 768px) {
  .diagram-renderer {
    grid-template-columns: 1fr;
  }
}
</style>
